---
booktitle: Proceedings of the Fourteenth International Conference on Artificial Intelligence
  and Statistics
publisher: JMLR Workshop and Conference Proceedings
logoright: basic_files/SAIS_logo.jpg
volume: 15
year: '2011'
shortname: AISTATS
start: 2011-04-11
end: 2011-04-13
published: 2011-06-14
month: 0
sections:
- name: preface
  title: Preface
- name: notable
  title: 'Part I: Notable Papers'
- name: default
  title: 'Part II: Regular Papers'
layout: proceedings
series: Proceedings of Machine Learning Research
id: GordonAISTATS2011
cycles: false
editor:
- given: Geoffrey
  family: Gordon
- given: David
  family: Dunson
- given: Miroslav
  family: Dudík
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Fourteenth International Conference on Artificial Intelligence and Statistics
    Held in Fort Lauderdale, FL, USA on 11-13 April 2011

  Published as Volume 15 by the Proceedings of Machine Learning Research on 14 June 2011.

  Volume Edited by:
    Geoffrey Gordon
    David Dunson
    Miroslav Dudík

  Series Editors:
    Neil D. Lawrence
date_str: 11--13 Apr
url: http://proceedings.mlr.press
baseurl: "/v15"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v15
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
email: ''
conference:
  name: Proceedings of the Fourteenth International Conference on Artificial Intelligence
    and Statistics
  url: 
  location: Fort Lauderdale, FL, USA
  dates:
  - 2011-04-11
  - 2011-04-12
  - 2011-04-13
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from v15.bib
---
